CREATE TABLE profile
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255),
    CONSTRAINT pk_profile PRIMARY KEY (id)
);

CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    reason      VARCHAR(255),
    location    VARCHAR(255),
    profile_id  BIGINT,
    created     VARCHAR(255),
    start       VARCHAR(255),
    "end"       VARCHAR(255),
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE profile
    ADD CONSTRAINT uc_profile_username UNIQUE (username);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_PROFILE FOREIGN KEY (profile_id) REFERENCES profile (id);