CREATE TABLE soldier
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    rank       VARCHAR(255),
    squad      VARCHAR(255),
    team       VARCHAR(255),
    role       VARCHAR(255),
    CONSTRAINT pk_soldier PRIMARY KEY (id)
);